
import islem.ButtonAyarlar;
import islem.Duzenleyici;
import islem.TextAyarlar;
import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class ogrenciekle extends javax.swing.JFrame implements Duzenleyici{
    DefaultListModel model; //model sayfanin her yerinde kullanmak için 
   
    public ogrenciekle() {
        initComponents();
        getEdite(); //uygulama yaparken duzenleme yapmak için method tekrarı olmasındıye
        model=new DefaultListModel(); //model olusturuldu.    ek bilgi:swing kendisi bir modeldi
        lststudent.setModel(model); //listte modeli attadik list içi temizlendi
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtname = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        btnekle = new javax.swing.JButton();
        btnsil = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lststudent = new javax.swing.JList<>();
        lblmesaj = new javax.swing.JLabel();
        btnuygulama = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student_Add");

        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblname.setText("Student Add: ");

        btnekle.setBackground(new java.awt.Color(0, 102, 0));
        btnekle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnekle.setText("Add");
        btnekle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnekle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnekleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnekleMouseExited(evt);
            }
        });
        btnekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnekleActionPerformed(evt);
            }
        });

        btnsil.setBackground(new java.awt.Color(255, 0, 0));
        btnsil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsil.setText("Delete");
        btnsil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnsilMouseExited(evt);
            }
        });
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        btnremove.setBackground(new java.awt.Color(255, 102, 102));
        btnremove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnremove.setText("Delete_Selected");
        btnremove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnremoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnremoveMouseExited(evt);
            }
        });
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        lststudent.setBackground(new java.awt.Color(204, 255, 204));
        lststudent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lststudent.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lststudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(lststudent);

        lblmesaj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblmesaj.setForeground(new java.awt.Color(0, 102, 102));

        btnuygulama.setBackground(new java.awt.Color(0, 204, 204));
        btnuygulama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnuygulama.setText("Next Application");
        btnuygulama.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnuygulama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnuygulamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnuygulamaMouseExited(evt);
            }
        });
        btnuygulama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuygulamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblname)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnremove)
                                .addGap(30, 30, 30)
                                .addComponent(btnuygulama))
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsil)
                        .addGap(338, 338, 338))))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsil)
                    .addComponent(btnremove)
                    .addComponent(btnuygulama)
                    .addComponent(btnekle))
                .addGap(30, 30, 30)
                .addComponent(lblmesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    @Override
    public void getEdite() {
       this.setLocationRelativeTo(null);//pencere ortada acilsin
        lststudent.setFocusable(true);//text field yazı yazma imlecini yok ettik
        TextAyarlar.setMaxLimit(txtname, 20); //karakter sınırlaması text field 20 karakter 
       
    }
    private void setBgFg(Component c){ //button uzerine gelindiğinde arka plan rengi değişi mi ve button yazı rengi değişi mi
        ButtonAyarlar.setBgFg((JButton) c,Color.BLACK, Color.WHITE); //arkaplan renk,yazırengi
    }
    //btnekle tıklandığındaki işlemler altta
    private void btnekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnekleActionPerformed
        if(!txtname.getText().equals("")){      //text field name mi txtname olan textfield dolu mu
           model.addElement(txtname.getText());//model olarak list almiştik yukarda.modele add element diyerek veri  ekleme yapmatıktı.txtnameiçinde veri ekledik.
           lblmesaj.setText("Kayit Eklendi: "+txtname.getText()); //label name mi lblmesaj olan label şu yaz (kayıt eklendi + txtname içinde yazı alındı(txtname.getText) )
           txtname.setText(""); //txtname içindekilerini silmek için
        }else{
            JOptionPane.showMessageDialog(this, "Eklenmedi.\n"+"Text kutusu boş ?");            
        }
    }//GEN-LAST:event_btnekleActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
        if(!txtname.getText().equals("")){  
           model.removeElement(txtname.getText()); //verilme işlemi(txtname içinde yazılan veri listeden silinir)
           lblmesaj.setText("Kayit Silindi: "+txtname.getText());
           txtname.setText("");
        }else{
             JOptionPane.showMessageDialog(this,"Silinemedi.\n"+"Text kutusu boş ?"); //açılır pencerede mesaj verme 
        }   
    }//GEN-LAST:event_btnsilActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        int index=lststudent.getSelectedIndex(); //secilen ad yok mu yoksa -1 dondurur
        if(index !=-1){
            model.removeElementAt(index);//secili elemanin index verilerek silme
            lblmesaj.setText("Seçili Eleman Silindi");                       
        }else if(index==-1){
            JOptionPane.showMessageDialog(this, "Silinemedi.\n"+"Seçili eleman yok ?");                        
        }
    }//GEN-LAST:event_btnremoveActionPerformed
    //button ustune gelindiğinde verilen arkaplan rengi ve yazı rengi degistirme
    private void btnekleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnekleMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_btnekleMouseEntered
   //buttonun ustunde gidildiğinde eski arkaplan rengi ve yazı rengi verilmesi
    private void btnekleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnekleMouseExited
         ButtonAyarlar.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_btnekleMouseExited

    private void btnsilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsilMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_btnsilMouseEntered

    private void btnsilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsilMouseExited
        ButtonAyarlar.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_btnsilMouseExited

    private void btnremoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremoveMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_btnremoveMouseEntered

    private void btnremoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremoveMouseExited
        ButtonAyarlar.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_btnremoveMouseExited

    private void btnuygulamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuygulamaMouseEntered
        this.setBgFg(evt.getComponent());
    }//GEN-LAST:event_btnuygulamaMouseEntered

    private void btnuygulamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnuygulamaMouseExited
       ButtonAyarlar.setOriginalBgFg((JButton) evt.getComponent());
    }//GEN-LAST:event_btnuygulamaMouseExited

    private void btnuygulamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuygulamaActionPerformed
        ButtonAyarlar.setVisible(this,new resimekle());//diğer uygulamaya gecmek için
    }//GEN-LAST:event_btnuygulamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ogrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ogrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ogrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogrenciekle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ogrenciekle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnekle;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton btnuygulama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmesaj;
    private javax.swing.JLabel lblname;
    private javax.swing.JList<String> lststudent;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

}
